In [2]:
import pandas as pd
import sklearn
from sklearn.impute import SimpleImputer
from sklearn import preprocessing
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

In [3]:
#import each of the datasets 

df1 = pd.read_csv('../thorax_and_wing_traits.csv')
df2 = pd.read_csv('../wing_asymmetry.csv')
df3 = pd.read_csv('../wing_traits_and_asymmetry.csv')

In [4]:
#no of datapoints in each file
print("Number of datapoints in thorax_and_wing_traits.csv: ", df1.shape[0])
print("Number of datapoints in wing_asymmetry.csv: ", df2.shape[0])
print("Number of datapoints in wing_traits_and_asymmetry.csv: ", df3.shape[0])

# Number of datapoints in thorax_and_wing_traits.csv:  1731
# Number of datapoints in wing_asymmetry.csv:  1727
# Number of datapoints in wing_traits_and_asymmetry.csv:  1731

Number of datapoints in thorax_and_wing_traits.csv:  1731
Number of datapoints in wing_asymmetry.csv:  1727
Number of datapoints in wing_traits_and_asymmetry.csv:  1731

In [7]:
# # Check unique combinations of vial, replicate, and sex in each file - are there the same number of datapoints?
unique_combinations_df1 = df1.groupby(['Species','Population','Temperature', 'Vial', 'Replicate', 'Sex']).size().reset_index(name='count')
unique_combinations_df2 = df2.groupby(['Species','Population','Temperature', 'Vial', 'Replicate', 'Sex']).size().reset_index(name='count')
unique_combinations_df3 = df3.groupby(['Species','Population','Temperature', 'Vial', 'Replicate', 'Sex']).size().reset_index(name='count')


print(unique_combinations_df1)
print(unique_combinations_df2)
print(unique_combinations_df3)


# Number of unique datapoints in thorax_and_wing_traits.csv (df1):  1731
# Number of unique datapoints in wing_asymmetry.csv (df2):  1727
# Number of unique datapoints in wing_traits_and_asymmetry.csv(df3):  1731

          Species Population  Temperature  Vial  Replicate     Sex  count
0     D._aldrichi    Binjour           20     1          1  female      1
1     D._aldrichi    Binjour           20     1          1    male      1
2     D._aldrichi    Binjour           20     1          2  female      1
3     D._aldrichi    Binjour           20     1          2    male      1
4     D._aldrichi    Binjour           20     2          1  female      1
...           ...        ...          ...   ...        ...     ...    ...
1726  D._buzzatii    Wahruna           30    10          1    male      1
1727  D._buzzatii    Wahruna           30    10          2  female      1
1728  D._buzzatii    Wahruna           30    10          2    male      1
1729  D._buzzatii    Wahruna           30    10          3  female      1
1730  D._buzzatii    Wahruna           30    10          3    male      1

[1731 rows x 7 columns]
          Species Population  Temperature  Vial  Replicate     Sex  count
0     D._aldrichi    Binjour           20     1          1  female      1
1     D._aldrichi    Binjour           20     1          1    male      1
2     D._aldrichi    Binjour           20     1          2  female      1
3     D._aldrichi    Binjour           20     1          2    male      1
4     D._aldrichi    Binjour           20     2          1  female      1
...           ...        ...          ...   ...        ...     ...    ...
1722  D._buzzatii    Wahruna           30    10          1    male      1
1723  D._buzzatii    Wahruna           30    10          2  female      1
1724  D._buzzatii    Wahruna           30    10          2    male      1
1725  D._buzzatii    Wahruna           30    10          3  female      1
1726  D._buzzatii    Wahruna           30    10          3    male      1

[1727 rows x 7 columns]
         Species Population  Temperature  Vial  Replicate     Sex  count
0     D.aldrichi    Binjour           20     1          1  female      1
1     D.aldrichi    Binjour           20     1          1    male      1
2     D.aldrichi    Binjour           20     1          2  female      1
3     D.aldrichi    Binjour           20     1          2    male      1
4     D.aldrichi    Binjour           20     2          1  female      1
...          ...        ...          ...   ...        ...     ...    ...
1726  D.buzzatii    Wahruna           30    10          1    male      1
1727  D.buzzatii    Wahruna           30    10          2  female      1
1728  D.buzzatii    Wahruna           30    10          2    male      1
1729  D.buzzatii    Wahruna           30    10          3  female      1
1730  D.buzzatii    Wahruna           30    10          3    male      1

[1731 rows x 7 columns]

In [8]:
# can see that the third file lists species in a different way, so lets make them all match. 
# i like the . better than the _ so we'll use that

df1['Species'] = df1['Species'].str.replace('_', '')
df2['Species'] = df2['Species'].str.replace('_', '')

In [15]:
# combine them into one big df
combined_df = pd.concat([df1, df2, df3], ignore_index=True)

combined_df

#has 5189 rows which is 1731+1727+1731

,Species,Population,Latitude,Longitude,Year_start,Year_end,Temperature,Vial,Replicate,Sex,...,Asymmetry_l3,Asymmetry_w1,Asymmetry_w2,Asymmetry_w3,Wing_area,Wing_shape,Wing_vein,Asymmetry_wing_area,Asymmetry_wing_shape,Asymmetry_wing_vein
0,D.aldrichi,Binjour,-25.52,151.45,1994,1994,20,1,1,female,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,D.aldrichi,Binjour,-25.52,151.45,1994,1994,20,1,1,male,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,D.aldrichi,Binjour,-25.52,151.45,1994,1994,20,1,2,female,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,D.aldrichi,Binjour,-25.52,151.45,1994,1994,20,1,2,male,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,D.aldrichi,Binjour,-25.52,151.45,1994,1994,20,2,1,female,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5184,D.buzzatii,Wahruna,-25.20,151.17,1994,1994,30,10,1,male,...,NaN,NaN,NaN,NaN,0.719,2.346,2.479,0.015,0.058,0.021
5185,D.buzzatii,Wahruna,-25.20,151.17,1994,1994,30,10,2,female,...,NaN,NaN,NaN,NaN,0.866,2.305,2.584,0.011,0.055,0.099
5186,D.buzzatii,Wahruna,-25.20,151.17,1994,1994,30,10,2,male,...,NaN,NaN,NaN,NaN,0.741,2.197,2.607,0.009,0.011,0.134
5187,D.buzzatii,Wahruna,-25.20,151.17,1994,1994,30,10,3,female,...,NaN,NaN,NaN,NaN,0.840,2.254,2.582,0.015,0.065,0.008
5188,D.buzzatii,Wahruna,-25.20,151.17,1994,1994,30,10,3,male,...,NaN,NaN,NaN,NaN,0.804,2.251,2.439,0.022,0.044,0.039

In [36]:
#now lets check the number of unique datapoints in the combined df - it should still be 1731
unique_combined = combined_df.groupby(['Species','Population','Temperature', 'Vial', 'Replicate', 'Sex']).size().reset_index(name='count')


for col, row in unique_combined.iterrows():
    if row['count'] != 3:
        print(row)
    if '_' in row['Population']:
        print(row)
#still 1731 rows - so all files contain the same individuals 
#above lets us see which ones are missing from df2

Species           D.aldrichi
Population     Gogango_Creek
Temperature               20
Vial                       1
Replicate                  1
Sex                   female
count                      3
Name: 162, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               20
Vial                       1
Replicate                  1
Sex                     male
count                      3
Name: 163, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               20
Vial                       1
Replicate                  2
Sex                   female
count                      3
Name: 164, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               20
Vial                       1
Replicate                  2
Sex                     male
count                      3
Name: 165, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               20
Vial                       1
Replicate                  3
Sex                   female
count                      3
Name: 166, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               20
Vial                       2
Replicate                  1
Sex                   female
count                      3
Name: 167, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               20
Vial                       2
Replicate                  1
Sex                     male
count                      3
Name: 168, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               20
Vial                       2
Replicate                  2
Sex                   female
count                      3
Name: 169, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               20
Vial                       2
Replicate                  2
Sex                     male
count                      3
Name: 170, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               20
Vial                       2
Replicate                  3
Sex                   female
count                      3
Name: 171, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               20
Vial                       2
Replicate                  3
Sex                     male
count                      3
Name: 172, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               20
Vial                       3
Replicate                  1
Sex                   female
count                      3
Name: 173, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               20
Vial                       3
Replicate                  1
Sex                     male
count                      3
Name: 174, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               20
Vial                       3
Replicate                  2
Sex                   female
count                      3
Name: 175, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               20
Vial                       3
Replicate                  2
Sex                     male
count                      3
Name: 176, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               20
Vial                       3
Replicate                  3
Sex                   female
count                      3
Name: 177, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               20
Vial                       3
Replicate                  3
Sex                     male
count                      3
Name: 178, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               20
Vial                       4
Replicate                  1
Sex                   female
count                      3
Name: 179, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               20
Vial                       4
Replicate                  1
Sex                     male
count                      3
Name: 180, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               20
Vial                       4
Replicate                  2
Sex                   female
count                      3
Name: 181, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               20
Vial                       4
Replicate                  2
Sex                     male
count                      3
Name: 182, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               20
Vial                       4
Replicate                  3
Sex                   female
count                      3
Name: 183, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               20
Vial                       4
Replicate                  3
Sex                     male
count                      3
Name: 184, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               20
Vial                       5
Replicate                  1
Sex                   female
count                      3
Name: 185, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               20
Vial                       5
Replicate                  1
Sex                     male
count                      3
Name: 186, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               20
Vial                       5
Replicate                  2
Sex                   female
count                      3
Name: 187, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               20
Vial                       5
Replicate                  2
Sex                     male
count                      3
Name: 188, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               20
Vial                       5
Replicate                  3
Sex                   female
count                      3
Name: 189, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               20
Vial                       5
Replicate                  3
Sex                     male
count                      3
Name: 190, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               20
Vial                       6
Replicate                  1
Sex                   female
count                      3
Name: 191, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               20
Vial                       6
Replicate                  1
Sex                     male
count                      3
Name: 192, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               20
Vial                       6
Replicate                  2
Sex                   female
count                      3
Name: 193, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               20
Vial                       6
Replicate                  2
Sex                     male
count                      3
Name: 194, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               20
Vial                       6
Replicate                  3
Sex                   female
count                      3
Name: 195, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               20
Vial                       6
Replicate                  3
Sex                     male
count                      3
Name: 196, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               20
Vial                       7
Replicate                  1
Sex                   female
count                      3
Name: 197, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               20
Vial                       7
Replicate                  1
Sex                     male
count                      3
Name: 198, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               20
Vial                       7
Replicate                  2
Sex                   female
count                      3
Name: 199, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               20
Vial                       7
Replicate                  2
Sex                     male
count                      3
Name: 200, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               20
Vial                       7
Replicate                  3
Sex                   female
count                      3
Name: 201, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               20
Vial                       7
Replicate                  3
Sex                     male
count                      3
Name: 202, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               20
Vial                       8
Replicate                  1
Sex                   female
count                      3
Name: 203, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               20
Vial                       8
Replicate                  1
Sex                     male
count                      3
Name: 204, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               20
Vial                       8
Replicate                  2
Sex                   female
count                      3
Name: 205, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               20
Vial                       8
Replicate                  2
Sex                     male
count                      3
Name: 206, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               20
Vial                       8
Replicate                  3
Sex                   female
count                      3
Name: 207, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               20
Vial                       8
Replicate                  3
Sex                     male
count                      3
Name: 208, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               20
Vial                       9
Replicate                  1
Sex                   female
count                      3
Name: 209, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               20
Vial                       9
Replicate                  1
Sex                     male
count                      3
Name: 210, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               20
Vial                       9
Replicate                  2
Sex                   female
count                      3
Name: 211, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               20
Vial                       9
Replicate                  2
Sex                     male
count                      3
Name: 212, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               20
Vial                       9
Replicate                  3
Sex                   female
count                      3
Name: 213, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               20
Vial                       9
Replicate                  3
Sex                     male
count                      3
Name: 214, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               20
Vial                      10
Replicate                  1
Sex                   female
count                      3
Name: 215, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               20
Vial                      10
Replicate                  1
Sex                     male
count                      3
Name: 216, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               20
Vial                      10
Replicate                  2
Sex                   female
count                      3
Name: 217, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               20
Vial                      10
Replicate                  2
Sex                     male
count                      3
Name: 218, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               20
Vial                      10
Replicate                  3
Sex                     male
count                      3
Name: 219, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               25
Vial                       1
Replicate                  1
Sex                   female
count                      3
Name: 220, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               25
Vial                       1
Replicate                  1
Sex                     male
count                      3
Name: 221, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               25
Vial                       1
Replicate                  2
Sex                   female
count                      3
Name: 222, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               25
Vial                       1
Replicate                  2
Sex                     male
count                      3
Name: 223, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               25
Vial                       1
Replicate                  3
Sex                   female
count                      3
Name: 224, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               25
Vial                       1
Replicate                  3
Sex                     male
count                      3
Name: 225, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               25
Vial                       2
Replicate                  1
Sex                   female
count                      3
Name: 226, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               25
Vial                       2
Replicate                  1
Sex                     male
count                      3
Name: 227, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               25
Vial                       2
Replicate                  2
Sex                   female
count                      3
Name: 228, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               25
Vial                       2
Replicate                  2
Sex                     male
count                      3
Name: 229, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               25
Vial                       2
Replicate                  3
Sex                     male
count                      3
Name: 230, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               25
Vial                       3
Replicate                  1
Sex                   female
count                      3
Name: 231, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               25
Vial                       3
Replicate                  1
Sex                     male
count                      3
Name: 232, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               25
Vial                       3
Replicate                  2
Sex                   female
count                      3
Name: 233, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               25
Vial                       3
Replicate                  2
Sex                     male
count                      3
Name: 234, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               25
Vial                       3
Replicate                  3
Sex                   female
count                      3
Name: 235, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               25
Vial                       3
Replicate                  3
Sex                     male
count                      3
Name: 236, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               25
Vial                       4
Replicate                  1
Sex                   female
count                      3
Name: 237, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               25
Vial                       4
Replicate                  1
Sex                     male
count                      3
Name: 238, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               25
Vial                       4
Replicate                  2
Sex                   female
count                      3
Name: 239, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               25
Vial                       4
Replicate                  2
Sex                     male
count                      3
Name: 240, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               25
Vial                       4
Replicate                  3
Sex                   female
count                      3
Name: 241, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               25
Vial                       4
Replicate                  3
Sex                     male
count                      3
Name: 242, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               25
Vial                       5
Replicate                  1
Sex                   female
count                      3
Name: 243, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               25
Vial                       5
Replicate                  1
Sex                     male
count                      3
Name: 244, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               25
Vial                       5
Replicate                  2
Sex                   female
count                      3
Name: 245, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               25
Vial                       5
Replicate                  2
Sex                     male
count                      3
Name: 246, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               25
Vial                       5
Replicate                  3
Sex                   female
count                      3
Name: 247, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               25
Vial                       5
Replicate                  3
Sex                     male
count                      3
Name: 248, dtype: object
Species           D.aldrichi
Population     Gogango_Creek
Temperature               25
Vial                       6
Replicate                  1

In [35]:
unique_combined

         Species Population  Temperature  Vial  Replicate     Sex  count
0     D.aldrichi    Binjour           20     1          1  female      3
1     D.aldrichi    Binjour           20     1          1    male      3
2     D.aldrichi    Binjour           20     1          2  female      3
3     D.aldrichi    Binjour           20     1          2    male      3
4     D.aldrichi    Binjour           20     2          1  female      3
...          ...        ...          ...   ...        ...     ...    ...
1726  D.buzzatii    Wahruna           30    10          1    male      3
1727  D.buzzatii    Wahruna           30    10          2  female      3
1728  D.buzzatii    Wahruna           30    10          2    male      3
1729  D.buzzatii    Wahruna           30    10          3  female      3
1730  D.buzzatii    Wahruna           30    10          3    male      3

[1731 rows x 7 columns]

In [29]:
# create a dictionary to give each fly a unique integer id

# Initialize an empty dictionary to store the mappings
fly_mapping = {}
next_id = 1  # Start with ID 1

# Iterate over the rows of the DataFrame
for _, row in df1.iterrows():
    # Extract the values of the columns
    species = row['Species']
    population = row['Population']
    temperature = row['Temperature']
    vial = row['Vial']
    replicate = row['Replicate']
    sex = row['Sex']
    
    # Check if the combination of values already exists in the dictionary
    key = (species, population, temperature, vial, replicate, sex)
    if key not in fly_mapping:
        # If not, assign a new ID and add the combination to the dictionary
        fly_mapping[key] = next_id
        next_id += 1

In [54]:
# map the fly id to the combined df in a new column
combined_df['Fly_ID'] = 0 #there is no fly id 0, and this initialises it to be an int not a float 
i = 1
for index, row in combined_df.iterrows():
    key = (row['Species'], row['Population'], row['Temperature'], row['Vial'], row['Replicate'], row['Sex'])
    combined_df.at[index, 'Fly_ID'] = fly_mapping[key]

In [55]:
combined_df

,Species,Population,Latitude,Longitude,Year_start,Year_end,Temperature,Vial,Replicate,Sex,...,Asymmetry_w1,Asymmetry_w2,Asymmetry_w3,Wing_area,Wing_shape,Wing_vein,Asymmetry_wing_area,Asymmetry_wing_shape,Asymmetry_wing_vein,Fly_ID
0,D.aldrichi,Binjour,-25.52,151.45,1994,1994,20,1,1,female,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1,D.aldrichi,Binjour,-25.52,151.45,1994,1994,20,1,1,male,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2
2,D.aldrichi,Binjour,-25.52,151.45,1994,1994,20,1,2,female,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3
3,D.aldrichi,Binjour,-25.52,151.45,1994,1994,20,1,2,male,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4
4,D.aldrichi,Binjour,-25.52,151.45,1994,1994,20,2,1,female,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5184,D.buzzatii,Wahruna,-25.20,151.17,1994,1994,30,10,1,male,...,NaN,NaN,NaN,0.719,2.346,2.479,0.015,0.058,0.021,1727
5185,D.buzzatii,Wahruna,-25.20,151.17,1994,1994,30,10,2,female,...,NaN,NaN,NaN,0.866,2.305,2.584,0.011,0.055,0.099,1728
5186,D.buzzatii,Wahruna,-25.20,151.17,1994,1994,30,10,2,male,...,NaN,NaN,NaN,0.741,2.197,2.607,0.009,0.011,0.134,1729
5187,D.buzzatii,Wahruna,-25.20,151.17,1994,1994,30,10,3,female,...,NaN,NaN,NaN,0.840,2.254,2.582,0.015,0.065,0.008,1730
5188,D.buzzatii,Wahruna,-25.20,151.17,1994,1994,30,10,3,male,...,NaN,NaN,NaN,0.804,2.251,2.439,0.022,0.044,0.039,1731

In [57]:
# group the rows by Fly ID - using first() keeps the non NaN values where they exist
grouped_df = combined_df.groupby('Fly_ID').first().reset_index()

In [58]:
grouped_df

,Fly_ID,Species,Population,Latitude,Longitude,Year_start,Year_end,Temperature,Vial,Replicate,...,Asymmetry_l3,Asymmetry_w1,Asymmetry_w2,Asymmetry_w3,Wing_area,Wing_shape,Wing_vein,Asymmetry_wing_area,Asymmetry_wing_shape,Asymmetry_wing_vein
0,1,D.aldrichi,Binjour,-25.52,151.45,1994,1994,20,1,1,...,0.047,0.016,0.031,0.031,1.223,2.296,2.597,0.043,0.010,0.028
1,2,D.aldrichi,Binjour,-25.52,151.45,1994,1994,20,1,1,...,0.015,0.001,0.004,0.004,1.006,2.289,2.528,0.006,0.018,0.044
2,3,D.aldrichi,Binjour,-25.52,151.45,1994,1994,20,1,2,...,0.013,0.028,0.011,0.047,1.149,2.340,2.580,0.039,0.053,0.140
3,4,D.aldrichi,Binjour,-25.52,151.45,1994,1994,20,1,2,...,0.020,0.006,0.002,0.011,1.000,2.180,2.508,0.016,0.007,0.074
4,5,D.aldrichi,Binjour,-25.52,151.45,1994,1994,20,2,1,...,0.005,0.000,0.027,0.011,1.160,2.275,2.589,0.003,0.005,0.100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1726,1727,D.buzzatii,Wahruna,-25.20,151.17,1994,1994,30,10,1,...,0.003,0.018,0.007,0.003,0.719,2.346,2.479,0.015,0.058,0.021
1727,1728,D.buzzatii,Wahruna,-25.20,151.17,1994,1994,30,10,2,...,0.011,0.016,0.038,0.029,0.866,2.305,2.584,0.011,0.055,0.099
1728,1729,D.buzzatii,Wahruna,-25.20,151.17,1994,1994,30,10,2,...,0.006,0.007,0.007,0.009,0.741,2.197,2.607,0.009,0.011,0.134
1729,1730,D.buzzatii,Wahruna,-25.20,151.17,1994,1994,30,10,3,...,0.045,0.005,0.017,0.014,0.840,2.254,2.582,0.015,0.065,0.008
1730,1731,D.buzzatii,Wahruna,-25.20,151.17,1994,1994,30,10,3,...,0.008,0.020,0.006,0.021,0.804,2.251,2.439,0.022,0.044,0.039

In [59]:
# these are the number of null values remaining in each column - this matches the number of NaN values in the original files
# except that the NaN values from df2 are +4 due to the 4 missing datapoints. 
print(f"{grouped_df.isnull().sum()}\n")

Fly_ID                   0
Species                  0
Population               0
Latitude                 0
Longitude                0
Year_start               0
Year_end                 0
Temperature              0
Vial                     0
Replicate                0
Sex                      0
Thorax_length            0
l2                       0
l3p                      0
l3d                      0
lpd                      0
l3                       0
w1                       0
w2                       0
w3                       0
wing_loading             0
Asymmetry_l2            10
Asymmetry_l3p            5
Asymmetry_l3d           13
Asymmetry_lpd           14
Asymmetry_l3            14
Asymmetry_w1            19
Asymmetry_w2            16
Asymmetry_w3            18
Wing_area                1
Wing_shape              19
Wing_vein                6
Asymmetry_wing_area     26
Asymmetry_wing_shape    26
Asymmetry_wing_vein     14
dtype: int64

In [64]:
# export new data to a csv for importing into other files later 
grouped_df.to_csv('all_data.csv', index=False)